Traceback (most recent call last):
  File "C:\Users\gyrx-zhangxf\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 762, in set_page_load_timeout
    'pageLoad': int(float(time_to_wait) * 1000)})
  File "C:\Users\gyrx-zhangxf\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gyrx-zhangxf\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Missing 'type' parameter


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\start.py", line 76, in <module>
    exec(run)     ## 执行业务流
  File "<string>", line 5, in <module>
  File "D:\notecode\code\torpedo\github\testbaidu.py", line 26, in searchbaidu
    loads(browser,testUrl)
  File "D:\notecode\code\torpedo\github/modules\finddoit.py", line 269, in loads
    browser.set_page_load_timeout(timeouts)
  File "C:\Users\gyrx-zhangxf\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 766, in set_page_load_timeout
    'type': 'page load'})
  File "C:\Users\gyrx-zhangxf\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gyrx-zhangxf\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unrecognised timeout: page load

